/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    Accordion: typeof import('./src/components/Accordion/Accordion.vue')['default']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    Badge: typeof import('./src/components/Badge.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    GaugeChart: typeof import('./src/components/GaugeChart.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader/MainHeader.vue')['default']
    MainNav: typeof import('./src/components/MainNav/MainNav.vue')['default']
    MenuHamburger: typeof import('./src/components/MainHeader/MenuHamburger.vue')['default']
    Modal: typeof import('./src/components/Modal/Modal.vue')['default']
    ModalSteps: typeof import('./src/components/Modal/ModalSteps.vue')['default']
    NotificationButton: typeof import('./src/components/MainHeader/NotificationButton.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/MainHeader/SearchBar.vue')['default']
    Select: typeof import('./src/components/Select.vue')['default']
    SidePanel: typeof import('./src/components/SidePanel/SidePanel.vue')['default']
    Socials: typeof import('./src/components/Socials.vue')['default']
    Switch: typeof import('./src/components/Switch.vue')['default']
    UserProfile: typeof import('./src/components/MainHeader/UserProfile.vue')['default']
    ViewHeader: typeof import('./src/components/ViewHeader.vue')['default']
  }
}
